// Seed / ingestion catalog for the Network event hub.
//
// These entries stand in for what a live connector layer will return once
// partner APIs (Meetup, Eventbrite, LinkedIn Events, Devpost, community
// calendars) are authorised. Each entry carries its source attribution and a
// stable `external_id`, so the ingestion job can upsert idempotently and a real
// connector can later replace a source block without touching the UI.

export type SeedEvent = {
  external_id: string;
  title: string;
  organizer: string;
  source: string;
  event_type: "hackathon" | "workshop" | "networking" | "women_program" | "conference";
  day_offset: number;
  start_hour: number;
  duration_hours: number;
  format: "in_person" | "virtual" | "hybrid";
  city: string | null;
  country: string | null;
  lat: number | null;
  lng: number | null;
  cost: "free" | "paid";
  price_text: string;
  skill_tags: string[];
  url: string;
  description: string;
  cohort_going: number;
};

const ZH = { city: "Zurich", country: "CH", lat: 47.3769, lng: 8.5417 };
const BS = { city: "Basel", country: "CH", lat: 47.5596, lng: 7.5886 };
const GE = { city: "Geneva", country: "CH", lat: 46.2044, lng: 6.1432 };
const BE = { city: "Bern", country: "CH", lat: 46.948, lng: 7.4474 };
const LS = { city: "Lausanne", country: "CH", lat: 46.5197, lng: 6.6323 };
const BER = { city: "Berlin", country: "DE", lat: 52.52, lng: 13.405 };
const MUC = { city: "Munich", country: "DE", lat: 48.1351, lng: 11.582 };
const AMS = { city: "Amsterdam", country: "NL", lat: 52.3676, lng: 4.9041 };
const LDN = { city: "London", country: "GB", lat: 51.5072, lng: -0.1276 };
const ONLINE = { city: null, country: null, lat: null, lng: null };

export const SEED_EVENTS: SeedEvent[] = [
  {
    external_id: "meetup:zurich-react-evening",
    title: "React Zurich: Patterns that survive production",
    organizer: "React Zurich",
    source: "Meetup",
    event_type: "workshop",
    day_offset: 4,
    start_hour: 18,
    duration_hours: 3,
    format: "in_person",
    ...ZH,
    cost: "free",
    price_text: "Free",
    skill_tags: ["React", "TypeScript", "Testing"],
    url: "https://www.meetup.com/react-zurich/",
    description:
      "A hands-on evening on component boundaries, data fetching and the state patterns that hold up once a codebase grows. Bring a laptop; pairs welcome.",
    cohort_going: 6,
  },
  {
    external_id: "wit:women-in-react-workshop",
    title: "Women in React: build & deploy your first dashboard",
    organizer: "Women Who Code Zurich",
    source: "Women in Tech Community Calendar",
    event_type: "women_program",
    day_offset: 11,
    start_hour: 17,
    duration_hours: 4,
    format: "hybrid",
    ...ZH,
    cost: "free",
    price_text: "Free (donations welcome)",
    skill_tags: ["React", "TypeScript", "Accessibility"],
    url: "https://www.womenwhocode.com/",
    description:
      "Ship something real in one sitting: a filtered dashboard with loading and empty states, reviewed by engineers who do this daily. Beginners genuinely welcome.",
    cohort_going: 14,
  },
  {
    external_id: "eventbrite:swiss-data-night",
    title: "Swiss Data Night: SQL to storytelling",
    organizer: "Data Community Switzerland",
    source: "Eventbrite",
    event_type: "networking",
    day_offset: 6,
    start_hour: 18,
    duration_hours: 3,
    format: "in_person",
    ...ZH,
    cost: "paid",
    price_text: "CHF 25",
    skill_tags: ["SQL", "Data Visualisation", "Stakeholder communication"],
    url: "https://www.eventbrite.com/",
    description:
      "Two short talks on turning messy operational data into decisions, then long, unhurried mingling with analysts and data leads.",
    cohort_going: 9,
  },
  {
    external_id: "devpost:femtech-hack",
    title: "FemTech Hack Europe (48h)",
    organizer: "FemTech Collective",
    source: "Devpost",
    event_type: "hackathon",
    day_offset: 19,
    start_hour: 9,
    duration_hours: 48,
    format: "hybrid",
    ...BER,
    cost: "free",
    price_text: "Free",
    skill_tags: ["React", "Python", "Product thinking"],
    url: "https://devpost.com/hackathons",
    description:
      "Weekend build sprint on women's health and care tech. Teams form on site, mentors circulate, and every team demos — a portfolio piece in two days.",
    cohort_going: 21,
  },
  {
    external_id: "meetup:python-basel",
    title: "PyBasel: pandas for people who inherited the spreadsheet",
    organizer: "PyBasel",
    source: "Meetup",
    event_type: "workshop",
    day_offset: 9,
    start_hour: 18,
    duration_hours: 2,
    format: "in_person",
    ...BS,
    cost: "free",
    price_text: "Free",
    skill_tags: ["Python", "SQL", "Data Visualisation"],
    url: "https://www.meetup.com/pybasel/",
    description:
      "A practical clinic: load ugly CSVs, clean them, and produce one chart you'd actually show a stakeholder.",
    cohort_going: 4,
  },
  {
    external_id: "linkedin:cloud-fundamentals-live",
    title: "Cloud fundamentals live: your first deploy on AWS",
    organizer: "Cloud Guild EU",
    source: "LinkedIn Events",
    event_type: "workshop",
    day_offset: 3,
    start_hour: 17,
    duration_hours: 2,
    format: "virtual",
    ...ONLINE,
    cost: "free",
    price_text: "Free",
    skill_tags: ["Cloud", "Docker", "AWS"],
    url: "https://www.linkedin.com/events/",
    description:
      "From empty account to a running container, narrated slowly. Perfect if cloud has always felt like someone else's job.",
    cohort_going: 17,
  },
  {
    external_id: "eventbrite:women-in-cloud-summit",
    title: "Women in Cloud Summit",
    organizer: "Women in Cloud",
    source: "Eventbrite",
    event_type: "conference",
    day_offset: 27,
    start_hour: 9,
    duration_hours: 9,
    format: "in_person",
    ...AMS,
    cost: "paid",
    price_text: "EUR 89 (scholarships available)",
    skill_tags: ["Cloud", "AWS", "Leadership"],
    url: "https://www.eventbrite.com/",
    description:
      "A full day of cloud architecture and career talks, with a hiring corner and a scholarship pool for career changers.",
    cohort_going: 11,
  },
  {
    external_id: "meetup:zurich-ml-reading",
    title: "ML Reading Circle: one paper, plainly explained",
    organizer: "Zurich ML Circle",
    source: "Meetup",
    event_type: "networking",
    day_offset: 8,
    start_hour: 19,
    duration_hours: 2,
    format: "in_person",
    ...ZH,
    cost: "free",
    price_text: "Free",
    skill_tags: ["Machine Learning", "Python", "Statistics"],
    url: "https://www.meetup.com/",
    description:
      "No maths bravado. One recent paper, explained so a careful beginner follows it, then coffee and questions.",
    cohort_going: 5,
  },
  {
    external_id: "partner:sponsor-office-hours",
    title: "Sponsor office hours: portfolio reviews with hiring engineers",
    organizer: "Hike Copilot Partner Network",
    source: "Sponsor & Partner Calendar",
    event_type: "women_program",
    day_offset: 5,
    start_hour: 12,
    duration_hours: 3,
    format: "virtual",
    ...ONLINE,
    cost: "free",
    price_text: "Free for members",
    skill_tags: ["Portfolio", "Interviewing", "React"],
    url: "https://ada.example.com/office-hours",
    description:
      "Book a 20-minute slot and have an engineer read your repo like a hiring manager would — then tell you the two things to change.",
    cohort_going: 8,
  },
  {
    external_id: "eventbrite:product-thinking-lab",
    title: "Product thinking lab for engineers",
    organizer: "Product Folks Zurich",
    source: "Eventbrite",
    event_type: "workshop",
    day_offset: 14,
    start_hour: 18,
    duration_hours: 3,
    format: "in_person",
    ...ZH,
    cost: "paid",
    price_text: "CHF 40",
    skill_tags: ["Product thinking", "Stakeholder communication"],
    url: "https://www.eventbrite.com/",
    description:
      "Practise the part of the job nobody teaches: scoping, saying no kindly, and explaining trade-offs to non-engineers.",
    cohort_going: 3,
  },
  {
    external_id: "meetup:geneva-frontend",
    title: "Geneva Frontend: accessibility from the first commit",
    organizer: "Geneva Frontend",
    source: "Meetup",
    event_type: "workshop",
    day_offset: 16,
    start_hour: 18,
    duration_hours: 2,
    format: "in_person",
    ...GE,
    cost: "free",
    price_text: "Free",
    skill_tags: ["Accessibility", "React", "Testing"],
    url: "https://www.meetup.com/",
    description:
      "Screen-reader demos and keyboard-only navigation, then fixing a real component together.",
    cohort_going: 2,
  },
  {
    external_id: "wit:she-codes-mixer-bern",
    title: "She Codes Bern: after-work mixer",
    organizer: "She Codes Bern",
    source: "Women in Tech Community Calendar",
    event_type: "networking",
    day_offset: 7,
    start_hour: 18,
    duration_hours: 3,
    format: "in_person",
    ...BE,
    cost: "free",
    price_text: "Free",
    skill_tags: ["Networking", "Career change"],
    url: "https://www.womenwhocode.com/",
    description:
      "No talks, no badges — just women in tech at every stage, a long table, and permission to ask beginner questions out loud.",
    cohort_going: 12,
  },
  {
    external_id: "devpost:open-data-hack-lausanne",
    title: "Open Data Hack Lausanne",
    organizer: "EPFL Open Data",
    source: "Devpost",
    event_type: "hackathon",
    day_offset: 24,
    start_hour: 10,
    duration_hours: 30,
    format: "in_person",
    ...LS,
    cost: "free",
    price_text: "Free (meals included)",
    skill_tags: ["Python", "SQL", "Data Visualisation"],
    url: "https://devpost.com/hackathons",
    description:
      "Public transport and climate datasets, friendly mentors, and a demo slot that makes a lovely portfolio entry.",
    cohort_going: 7,
  },
  {
    external_id: "linkedin:interview-clinic",
    title: "Technical interview clinic: think out loud without panic",
    organizer: "Careers in Code",
    source: "LinkedIn Events",
    event_type: "workshop",
    day_offset: 2,
    start_hour: 17,
    duration_hours: 2,
    format: "virtual",
    ...ONLINE,
    cost: "free",
    price_text: "Free",
    skill_tags: ["Interviewing", "Algorithms", "Communication"],
    url: "https://www.linkedin.com/events/",
    description:
      "Two mock interviews performed live, including a wrong turn and a recovery — so you see that stumbling is survivable.",
    cohort_going: 19,
  },
  {
    external_id: "eventbrite:women-in-data-conf",
    title: "Women in Data Conference",
    organizer: "Women in Data EU",
    source: "Eventbrite",
    event_type: "conference",
    day_offset: 33,
    start_hour: 9,
    duration_hours: 8,
    format: "hybrid",
    ...MUC,
    cost: "paid",
    price_text: "EUR 120 (early bird EUR 75)",
    skill_tags: ["SQL", "Python", "Machine Learning", "Data Visualisation"],
    url: "https://www.eventbrite.com/",
    description:
      "Analytics, ML in production, and a candid track on switching into data from another career entirely.",
    cohort_going: 15,
  },
  {
    external_id: "meetup:docker-k8s-evening",
    title: "Containers, calmly: Docker and a first Kubernetes deploy",
    organizer: "Cloud Native Zurich",
    source: "Meetup",
    event_type: "workshop",
    day_offset: 13,
    start_hour: 18,
    duration_hours: 3,
    format: "in_person",
    ...ZH,
    cost: "free",
    price_text: "Free",
    skill_tags: ["Docker", "Cloud", "DevOps"],
    url: "https://www.meetup.com/",
    description: "Build an image, break it, fix it, deploy it. Ideal before a cloud certification attempt.",
    cohort_going: 6,
  },
  {
    external_id: "partner:cv-and-linkedin-lab",
    title: "Swiss CV & LinkedIn lab",
    organizer: "Hike Copilot Partner Network",
    source: "Sponsor & Partner Calendar",
    event_type: "women_program",
    day_offset: 10,
    start_hour: 12,
    duration_hours: 2,
    format: "virtual",
    ...ONLINE,
    cost: "free",
    price_text: "Free for members",
    skill_tags: ["Portfolio", "Networking", "Career change"],
    url: "https://ada.example.com/cv-lab",
    description:
      "Bring the CV you already have. We rework it to Swiss conventions live, then tidy your LinkedIn headline together.",
    cohort_going: 10,
  },
  {
    external_id: "meetup:testing-guild",
    title: "Testing Guild: from zero tests to a suite you trust",
    organizer: "Testing Guild EU",
    source: "Meetup",
    event_type: "workshop",
    day_offset: 21,
    start_hour: 17,
    duration_hours: 2,
    format: "virtual",
    ...ONLINE,
    cost: "free",
    price_text: "Free",
    skill_tags: ["Testing", "TypeScript", "React"],
    url: "https://www.meetup.com/",
    description: "Where to put your first three tests so they catch real bugs instead of ceremony.",
    cohort_going: 5,
  },
  {
    external_id: "eventbrite:london-women-tech-mixer",
    title: "Women in Tech London: hiring mixer",
    organizer: "Tech Women London",
    source: "Eventbrite",
    event_type: "networking",
    day_offset: 18,
    start_hour: 18,
    duration_hours: 3,
    format: "in_person",
    ...LDN,
    cost: "paid",
    price_text: "GBP 15",
    skill_tags: ["Networking", "Interviewing", "React"],
    url: "https://www.eventbrite.co.uk/",
    description: "Small-group conversations with engineers from teams actively hiring — no CV drop, just talking.",
    cohort_going: 13,
  },
  {
    external_id: "devpost:ai-for-good-sprint",
    title: "AI for Good weekend sprint",
    organizer: "AI for Good Lab",
    source: "Devpost",
    event_type: "hackathon",
    day_offset: 30,
    start_hour: 9,
    duration_hours: 36,
    format: "virtual",
    ...ONLINE,
    cost: "free",
    price_text: "Free",
    skill_tags: ["Python", "Machine Learning", "Cloud"],
    url: "https://devpost.com/hackathons",
    description:
      "Remote teams, NGO briefs, and mentors on call. First-time hackers get paired deliberately, not left to fend.",
    cohort_going: 16,
  },
  {
    external_id: "wit:mums-in-tech-returners",
    title: "Returners circle: back into tech after a break",
    organizer: "Mums in Tech CH",
    source: "Women in Tech Community Calendar",
    event_type: "women_program",
    day_offset: 12,
    start_hour: 10,
    duration_hours: 2,
    format: "hybrid",
    ...ZH,
    cost: "free",
    price_text: "Free",
    skill_tags: ["Career change", "Networking", "Interviewing"],
    url: "https://www.womenwhocode.com/",
    description:
      "A gentle, practical circle on returning after time out: how to frame the gap, and who is genuinely welcoming.",
    cohort_going: 9,
  },
  {
    external_id: "meetup:sql-clinic-online",
    title: "SQL clinic: window functions without fear",
    organizer: "SQL Study Group",
    source: "Meetup",
    event_type: "workshop",
    day_offset: 1,
    start_hour: 18,
    duration_hours: 2,
    format: "virtual",
    ...ONLINE,
    cost: "free",
    price_text: "Free",
    skill_tags: ["SQL", "Data Visualisation"],
    url: "https://www.meetup.com/",
    description: "One query, built up line by line, until window functions stop looking like hieroglyphs.",
    cohort_going: 8,
  },
  {
    external_id: "linkedin:public-speaking-tech",
    title: "Speaking up: your first tech talk",
    organizer: "Speak Easy Tech",
    source: "LinkedIn Events",
    event_type: "women_program",
    day_offset: 23,
    start_hour: 17,
    duration_hours: 2,
    format: "virtual",
    ...ONLINE,
    cost: "free",
    price_text: "Free",
    skill_tags: ["Communication", "Networking", "Portfolio"],
    url: "https://www.linkedin.com/events/",
    description:
      "Draft a five-minute talk from something you already built, and practise it once in a room that is on your side.",
    cohort_going: 11,
  },
  {
    external_id: "eventbrite:zurich-tech-careers-fair",
    title: "Zurich Tech Careers Fair",
    organizer: "Swiss Tech Careers",
    source: "Eventbrite",
    event_type: "conference",
    day_offset: 36,
    start_hour: 10,
    duration_hours: 7,
    format: "in_person",
    ...ZH,
    cost: "free",
    price_text: "Free with registration",
    skill_tags: ["Interviewing", "Networking", "React", "SQL"],
    url: "https://www.eventbrite.com/",
    description: "Forty teams hiring in Switzerland, plus a quiet room and a CV desk if the hall gets loud.",
    cohort_going: 20,
  },
  {
    external_id: "meetup:amsterdam-node-api",
    title: "APIs that age well: Node & Postgres evening",
    organizer: "Amsterdam Backend",
    source: "Meetup",
    event_type: "workshop",
    day_offset: 20,
    start_hour: 18,
    duration_hours: 3,
    format: "in_person",
    ...AMS,
    cost: "free",
    price_text: "Free",
    skill_tags: ["SQL", "TypeScript", "APIs"],
    url: "https://www.meetup.com/",
    description: "Design an endpoint together, argue about pagination, leave with a pattern you can reuse.",
    cohort_going: 4,
  },
  {
    external_id: "partner:mock-interview-marathon",
    title: "Mock interview marathon (women-only cohort)",
    organizer: "Hike Copilot Partner Network",
    source: "Sponsor & Partner Calendar",
    event_type: "women_program",
    day_offset: 26,
    start_hour: 9,
    duration_hours: 6,
    format: "virtual",
    ...ONLINE,
    cost: "free",
    price_text: "Free for members",
    skill_tags: ["Interviewing", "Algorithms", "Communication"],
    url: "https://ada.example.com/mock-interviews",
    description:
      "Three interviews, three kinds of feedback, one day. You leave with notes instead of a vague bad feeling.",
    cohort_going: 14,
  },
  {
    external_id: "meetup:munich-react-native",
    title: "Munich React: performance profiling live",
    organizer: "React Munich",
    source: "Meetup",
    event_type: "workshop",
    day_offset: 29,
    start_hour: 18,
    duration_hours: 2,
    format: "in_person",
    ...MUC,
    cost: "free",
    price_text: "Free",
    skill_tags: ["React", "TypeScript", "Testing"],
    url: "https://www.meetup.com/",
    description: "Profile a slow list on stage, find the re-render, fix it. Concrete and oddly satisfying.",
    cohort_going: 3,
  },
  {
    external_id: "eventbrite:geneva-cloud-cert-bootcamp",
    title: "Cloud certification bootcamp (AWS SAA)",
    organizer: "Alpine Cloud Academy",
    source: "Eventbrite",
    event_type: "workshop",
    day_offset: 31,
    start_hour: 9,
    duration_hours: 8,
    format: "hybrid",
    ...GE,
    cost: "paid",
    price_text: "CHF 190",
    skill_tags: ["Cloud", "AWS", "Docker"],
    url: "https://www.eventbrite.com/",
    description: "A structured run at the exam blueprint, with practice questions and a study plan to take home.",
    cohort_going: 6,
  },
  {
    external_id: "wit:coffee-pairs-virtual",
    title: "Virtual coffee pairs: 30 minutes, one new person",
    organizer: "Women in Tech CH",
    source: "Women in Tech Community Calendar",
    event_type: "networking",
    day_offset: 5,
    start_hour: 8,
    duration_hours: 1,
    format: "virtual",
    ...ONLINE,
    cost: "free",
    price_text: "Free",
    skill_tags: ["Networking", "Career change"],
    url: "https://www.womenwhocode.com/",
    description:
      "You get matched with one woman in tech and a prompt to start from. The lowest-effort way to grow a network.",
    cohort_going: 18,
  },
  {
    external_id: "devpost:swiss-fintech-hack",
    title: "Swiss FinTech Hack",
    organizer: "FinTech Hub CH",
    source: "Devpost",
    event_type: "hackathon",
    day_offset: 40,
    start_hour: 9,
    duration_hours: 48,
    format: "in_person",
    ...ZH,
    cost: "free",
    price_text: "Free",
    skill_tags: ["Python", "SQL", "APIs", "Product thinking"],
    url: "https://devpost.com/hackathons",
    description: "Banking APIs, sandbox data, and judges who care more about the demo than the pitch deck.",
    cohort_going: 8,
  },
];
