/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MentorMatchRouteImport } from './routes/mentor-match'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as ApiPublicEventsRefreshRouteImport } from './routes/api/public/events/refresh'
import { Route as ApiPublicMentorsRemindersRouteImport } from './routes/api/public/mentors/reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorMatchRoute = MentorMatchRouteImport.update({
  id: '/mentor-match',
  path: '/mentor-match',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventsRefreshRoute = ApiPublicEventsRefreshRouteImport.update({
  id: '/api/public/events/refresh',
  path: '/api/public/events/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMentorsRemindersRoute =
  ApiPublicMentorsRemindersRouteImport.update({
    id: '/api/public/mentors/reminders',
    path: '/api/public/mentors/reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mentor-match': typeof MentorMatchRoute
  '/network': typeof NetworkRoute
  '/roadmap': typeof RoadmapRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/api/public/events/refresh': typeof ApiPublicEventsRefreshRoute
  '/api/public/mentors/reminders': typeof ApiPublicMentorsRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mentor-match': typeof MentorMatchRoute
  '/network': typeof NetworkRoute
  '/roadmap': typeof RoadmapRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/api/public/events/refresh': typeof ApiPublicEventsRefreshRoute
  '/api/public/mentors/reminders': typeof ApiPublicMentorsRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mentor-match': typeof MentorMatchRoute
  '/network': typeof NetworkRoute
  '/roadmap': typeof RoadmapRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/api/public/events/refresh': typeof ApiPublicEventsRefreshRoute
  '/api/public/mentors/reminders': typeof ApiPublicMentorsRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mentor-match'
    | '/network'
    | '/roadmap'
    | '/chat/$threadId'
    | '/api/public/events/refresh'
    | '/api/public/mentors/reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mentor-match'
    | '/network'
    | '/roadmap'
    | '/chat/$threadId'
    | '/api/public/events/refresh'
    | '/api/public/mentors/reminders'
  id:
    | '__root__'
    | '/'
    | '/mentor-match'
    | '/network'
    | '/roadmap'
    | '/chat/$threadId'
    | '/api/public/events/refresh'
    | '/api/public/mentors/reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MentorMatchRoute: typeof MentorMatchRoute
  NetworkRoute: typeof NetworkRoute
  RoadmapRoute: typeof RoadmapRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ApiPublicEventsRefreshRoute: typeof ApiPublicEventsRefreshRoute
  ApiPublicMentorsRemindersRoute: typeof ApiPublicMentorsRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-match': {
      id: '/mentor-match'
      path: '/mentor-match'
      fullPath: '/mentor-match'
      preLoaderRoute: typeof MentorMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/events/refresh': {
      id: '/api/public/events/refresh'
      path: '/api/public/events/refresh'
      fullPath: '/api/public/events/refresh'
      preLoaderRoute: typeof ApiPublicEventsRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mentors/reminders': {
      id: '/api/public/mentors/reminders'
      path: '/api/public/mentors/reminders'
      fullPath: '/api/public/mentors/reminders'
      preLoaderRoute: typeof ApiPublicMentorsRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MentorMatchRoute: MentorMatchRoute,
  NetworkRoute: NetworkRoute,
  RoadmapRoute: RoadmapRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
  ApiPublicEventsRefreshRoute: ApiPublicEventsRefreshRoute,
  ApiPublicMentorsRemindersRoute: ApiPublicMentorsRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
