ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS drawn_to TEXT,
  ADD COLUMN IF NOT EXISTS location_pref TEXT,
  ADD COLUMN IF NOT EXISTS work_setup TEXT[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS work_auth TEXT,
  ADD COLUMN IF NOT EXISTS recent_role TEXT,
  ADD COLUMN IF NOT EXISTS weekly_hours INTEGER,
  ADD COLUMN IF NOT EXISTS skill_confidence JSONB NOT NULL DEFAULT '[]'::jsonb;